<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #1a1a1a;
            padding: 30px;
            background: #fff;
        }

        /* ── HEADER ── */
        .header {
            text-align: center;
            border-bottom: 3px solid #1a1a2e;
            padding-bottom: 14px;
            margin-bottom: 18px;
        }
        .brand-name {
            font-size: 22px;
            font-weight: 700;
            color: #1a1a2e;
            letter-spacing: 1px;
        }
        .brand-sub {
            font-size: 11px;
            color: #555;
            margin-top: 2px;
        }
        .report-meta {
            text-align: center;
            font-size: 11px;
            color: #444;
            line-height: 1.7;
            margin-top: 8px;
        }
        .report-meta strong {
            color: #1a1a2e;
        }

        /* ── REPORT TITLE ── */
        .report-title {
            text-align: center;
            font-size: 16px;
            font-weight: 700;
            letter-spacing: 2px;
            color: #1a1a2e;
            margin-bottom: 18px;
            text-transform: uppercase;
        }

        /* ── STAT CARDS ── */
        .stat-row {
            width: 100%;
            margin-bottom: 20px;
            border-collapse: separate;
            border-spacing: 8px;
        }
        .stat-box {
            background: #1a1a2e;
            color: #fff;
            padding: 12px 10px;
            border-radius: 8px;
            text-align: center;
            width: 33%;
        }
        .stat-box .s-label {
            font-size: 10px;
            opacity: 0.75;
            text-transform: uppercase;
            letter-spacing: 1px;
            margin-bottom: 4px;
        }
        .stat-box .s-value {
            font-size: 20px;
            font-weight: 700;
        }

        /* ── SECTION TITLE ── */
        .section-title {
            font-size: 12px;
            font-weight: 700;
            letter-spacing: 1.5px;
            text-transform: uppercase;
            color: #1a1a2e;
            border-left: 4px solid #1a1a2e;
            padding-left: 8px;
            margin: 18px 0 8px;
        }

        /* ── TABLE ── */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 6px;
            font-size: 11px;
        }
        thead tr {
            background: #1a1a2e;
            color: #fff;
        }
        thead th {
            padding: 8px 10px;
            text-align: center;
            font-weight: 600;
            letter-spacing: 0.5px;
        }
        thead th:first-child { text-align: left; }
        tbody tr:nth-child(even) { background: #f5f7fa; }
        tbody td {
            padding: 7px 10px;
            border-bottom: 1px solid #e8ecf0;
            text-align: center;
        }
        tbody td:first-child { text-align: left; }
        .empty-row td {
            text-align: center;
            color: #888;
            padding: 12px;
        }

        /* ── FOOTER ── */
        .footer {
            margin-top: 24px;
            border-top: 1px solid #ccc;
            padding-top: 10px;
            display: flex;
            justify-content: space-between;
            font-size: 10px;
            color: #777;
        }
    </style>
</head>
<body>

    <!-- HEADER -->
    <div class="header">
        <div class="brand-name">BubbleBee Laundry</div>
        <div class="brand-sub">Reports & Analytics</div>
        <div class="report-meta">
            <strong>Generated by:</strong> {{ auth()->user()->name }}
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <strong>Date:</strong> {{ now('Asia/Manila')->format('F d, Y') }}
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <strong>Time:</strong> {{ now('Asia/Manila')->format('h:i A') }}
        </div>
    </div>

    <!-- TITLE -->
    <div class="report-title">Monthly Reports — {{ now('Asia/Manila')->format('F Y') }}</div>

    <!-- STAT CARDS -->
    <table class="stat-row">
        <tr>
            <td class="stat-box">
                <div class="s-label">Monthly Revenue</div>
                <div class="s-value">&#8369;{{ number_format($monthlyRevenue, 2) }}</div>
            </td>
            <td class="stat-box">
                <div class="s-label">Total Orders</div>
                <div class="s-value">{{ $totalOrders }}</div>
            </td>
            <td class="stat-box">
                <div class="s-label">Completed Orders</div>
                <div class="s-value">{{ $completed }}</div>
            </td>
        </tr>
    </table>

    <!-- SALES SUMMARY -->
    <div class="section-title">Sales Summary</div>
    <table>
        <thead>
            <tr>
                <th style="text-align:left;">Date</th>
                <th>Total Orders</th>
                <th>Completed</th>
                <th>Revenue</th>
                <th>Avg Order</th>
            </tr>
        </thead>
        <tbody>
            @forelse($salesSummary as $summary)
            <tr>
                <td>{{ \Carbon\Carbon::parse($summary->date)->format('M d, Y') }}</td>
                <td>{{ $summary->total_orders }}</td>
                <td>{{ $summary->completed }}</td>
                <td>&#8369;{{ number_format($summary->revenue, 2) }}</td>
                <td>&#8369;{{ $summary->total_orders > 0 ? number_format($summary->revenue / $summary->total_orders, 2) : '0.00' }}</td>
            </tr>
            @empty
            <tr class="empty-row"><td colspan="5">No data available</td></tr>
            @endforelse
        </tbody>
    </table>

    <!-- TOP SERVICES -->
    <div class="section-title">Top Services</div>
    <table>
        <thead>
            <tr>
                <th style="text-align:left;">Service</th>
                <th>Total Orders</th>
                <th>Revenue</th>
            </tr>
        </thead>
        <tbody>
            @forelse($topServices as $service)
            <tr>
                <td>{{ $service->service }}</td>
                <td>{{ $service->total }}</td>
                <td>&#8369;{{ number_format($service->revenue, 2) }}</td>
            </tr>
            @empty
            <tr class="empty-row"><td colspan="3">No data available</td></tr>
            @endforelse
        </tbody>
    </table>

    <!-- PAYMENT METHOD BREAKDOWN -->
    <div class="section-title">Payment Method Breakdown</div>
    <table>
        <thead>
            <tr>
                <th style="text-align:left;">Method</th>
                <th>Count</th>
                <th>Total Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse($paymentMethods as $method)
            <tr>
                <td>{{ $method->method }}</td>
                <td>{{ $method->count }}</td>
                <td>&#8369;{{ number_format($method->total, 2) }}</td>
            </tr>
            @empty
            <tr class="empty-row"><td colspan="3">No data available</td></tr>
            @endforelse
        </tbody>
    </table>

    <!-- TOP CUSTOMERS -->
    <div class="section-title">Top Customers</div>
    <table>
        <thead>
            <tr>
                <th style="text-align:left;">Customer</th>
                <th>Total Orders</th>
                <th>Total Spent</th>
            </tr>
        </thead>
        <tbody>
            @forelse($topCustomers as $customer)
            <tr>
                <td>{{ $customer->customer_name }}</td>
                <td>{{ $customer->total_orders }}</td>
                <td>&#8369;{{ number_format($customer->total_spent, 2) }}</td>
            </tr>
            @empty
            <tr class="empty-row"><td colspan="3">No data available</td></tr>
            @endforelse
        </tbody>
    </table>    
</body>
</html>